# Generated by Django 5.1 on 2024-08-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.CharField(default='Descanocido', max_length=100, verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
